# image: gitpod/workspace-dotnet
image:
  file: Dockerfile
tasks:
 - command: >
    echo Starting &&
    mssql-launch.sh

vscode:
  extensions:
    - mhutchie.git-graph@1.18.0:LzqJ/RuqakaRZud6LtvTQw==