# image: gitpod/workspace-dotnet
image:
  file: postgres.Dockerfile
# tasks:
#  - command: mssql-launch.sh
    - command: >
        echo DATABASE_URL=$DATABASE_URL >> .env &&
        pg_start.sh

vscode:
  extensions:
    - mhutchie.git-graph@1.18.0:LzqJ/RuqakaRZud6LtvTQw==