// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SimpleCRM.Data.Contexts;

namespace SimpleCRM.Data.Migrations
{
    [DbContext(typeof(CrmContext))]
    partial class CrmContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-rtm-30799");

            modelBuilder.Entity("SimpleCRM.Api.Models.EF._Label", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Created");

                    b.Property<int>("Custom");

                    b.Property<string>("Label");

                    b.HasKey("Id");

                    b.ToTable("Labels");
                });

            modelBuilder.Entity("SimpleCRM.Api.Models.EF.Entity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Created");

                    b.Property<int>("Custom");

                    b.Property<int?>("LabelId");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("Id");

                    b.HasIndex("LabelId");

                    b.ToTable("Entities");
                });

            modelBuilder.Entity("SimpleCRM.Api.Models.EF.Entity", b =>
                {
                    b.HasOne("SimpleCRM.Api.Models.EF._Label", "Label")
                        .WithMany("Entities")
                        .HasForeignKey("LabelId")
                        .HasConstraintName("FK_Entities_Labels");
                });
#pragma warning restore 612, 618
        }
    }
}
